{
 "title": "Networking / Linux Subsystem Stats",
 "tags": [
  "openshift",
  "networking",
  "linux-subsystem",
  "acm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "acm_label_names",
    "label": "Label",
    "query": "label_values(acm_label_names, label_name)"
   },
   {
    "name": "value",
    "label": "Value",
    "query": "label_values(acm_managed_cluster_labels, $acm_label_names)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(acm_managed_cluster_labels{$acm_label_names=~\"$value\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Receive Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current Transmit Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current Drops",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\"}[10m])) + sum by (cluster) (rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(container_network_receive_errors_total{cluster=~\"$cluster\"}[10m])) + sum by (cluster) (rate(container_network_transmit_errors_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Network Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Bytes Received, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Bytes Sent, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Bytes Received, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  },
  {
   "title": "Bytes Sent, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  },
  { "title": "Network Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Packets Received Dropped, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Packets Sent Dropped, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Packets Received Dropped, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  },
  {
   "title": "Packets Sent Dropped, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  },
  { "title": "Network Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Packets Received, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_receive_errors_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Packets Sent, by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, node) (rate(container_network_transmit_errors_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Packets Received, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_receive_errors_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  },
  {
   "title": "Packets Sent, by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cluster, dev) (label_replace(label_replace(rate(container_network_transmit_errors_total{cluster=~\"$cluster\"}[10m]), \"dev\", \"$1\", \"interface\", \"(.*)\"), \"dev\", \"(pod)\", \"interface\", \"[a-f0-9]{15}\"))",
     "legendFormat": "{{cluster}} {{dev}}"
    }
   ]
  }
 ]
}