{
 "title": "Networking / Ingress",
 "tags": [
  "openshift",
  "networking",
  "ingress",
  "haproxy",
  "acm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "acm_label_names",
    "label": "Label",
    "query": {
     "query": "label_values(acm_label_names, label_name)"
    }
   },
   {
    "name": "value",
    "label": "Value",
    "query": {
     "query": "label_values(acm_managed_cluster_labels, $acm_label_names)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels{$acm_label_names=~\"$value\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Total Incoming Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(haproxy_server_bytes_in_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current Total Outgoing Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(haproxy_server_bytes_out_total{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (increase(haproxy_server_http_responses_total{cluster=~\"$cluster\",code=~\"4xx|5xx\", route!=\"\"}[10m])) / sum by (cluster) (increase(haproxy_server_http_responses_total{cluster=~\"$cluster\",route!=\"\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "HTTP Server Average Response Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cluster) (haproxy_server_http_average_response_latency_milliseconds{cluster=~\"$cluster\"} != 0)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Top 10 Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, route) (rate(haproxy_server_bytes_in_total{cluster=~\"$cluster\",route!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{route}}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, route) (rate(haproxy_server_bytes_out_total{cluster=~\"$cluster\",route!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{route}}"
    }
   ]
  },
  {
   "title": "HTTP Server Response Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, route) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",code=~\"4xx|5xx\", route!=\"\"}[10m]) != 0) / sum by (cluster, route) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",route!=\"\"}[10m])))",
     "legendFormat": "{{cluster}} {{route}}"
    }
   ]
  },
  {
   "title": "Average HTTP Server Response Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, avg by (cluster, route) (haproxy_server_http_average_response_latency_milliseconds{cluster=~\"$cluster\",route!=\"\"} != 0) != 0)",
     "legendFormat": "{{cluster}} {{route}}"
    }
   ]
  },
  { "title": "Top 10 Per Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, exported_namespace) (rate(haproxy_server_bytes_in_total{cluster=~\"$cluster\",exported_namespace!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, exported_namespace) (rate(haproxy_server_bytes_out_total{cluster=~\"$cluster\",exported_namespace!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "HTTP Server Response Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, exported_namespace) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",code=~\"4xx|5xx\", route!=\"\"}[10m]) != 0) / sum by (cluster, exported_namespace) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",route!=\"\"}[10m])))",
     "legendFormat": "{{cluster}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Average HTTP Server Response Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, avg by (cluster, exported_namespace) (haproxy_server_http_average_response_latency_milliseconds{cluster=~\"$cluster\",exported_namespace!=\"\"} != 0) != 0)",
     "legendFormat": "{{cluster}} {{exported_namespace}}"
    }
   ]
  },
  { "title": "Top 10 Per Shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, service) (rate(haproxy_server_bytes_in_total{cluster=~\"$cluster\",route!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{service}}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, service) (rate(haproxy_server_bytes_out_total{cluster=~\"$cluster\",route!=\"\"}[10m])) != 0)",
     "legendFormat": "{{cluster}} {{service}}"
    }
   ]
  },
  {
   "title": "HTTP Server Response Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum by (cluster, service) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",code=~\"4xx|5xx\", route!=\"\"}[10m]) != 0) / sum by (cluster, service) (rate(haproxy_server_http_responses_total{cluster=~\"$cluster\",route!=\"\"}[10m])))",
     "legendFormat": "{{cluster}} {{service}}"
    }
   ]
  },
  {
   "title": "Average HTTP Server Response Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, avg by (cluster, service) (haproxy_server_http_average_response_latency_milliseconds{cluster=~\"$cluster\",route!=\"\"} != 0) != 0)",
     "legendFormat": "{{cluster}} {{service}}"
    }
   ]
  },
  {
   "title": "Number of Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, count by (cluster, service) (count by (cluster, route, service) (haproxy_server_up{cluster=~\"$cluster\"} == 1)) != 0)",
     "legendFormat": "{{cluster}} {{service}}"
    }
   ]
  }
 ]
}