{
 "title": "Networking / Infrastructure",
 "tags": [
  "openshift",
  "networking",
  "infrastructure",
  "ovn-kubernetes",
  "acm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "acm_label_names",
    "label": "Label",
    "query": {
     "query": "label_values(acm_label_names, label_name)"
    }
   },
   {
    "name": "value",
    "label": "Value",
    "query": {
     "query": "label_values(acm_managed_cluster_labels, $acm_label_names)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels{$acm_label_names=~\"$value\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Changes Per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(ovnkube_node_cni_request_duration_seconds_count{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (ovnkube_node_cni_request_duration_seconds_count{cluster=~\"$cluster\",err!=\"false\"}) / sum by (cluster) (ovnkube_node_cni_request_duration_seconds_count{cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Latency on Pod Creation, P99",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(cluster, le) (rate(ovnkube_node_cni_request_duration_seconds_bucket{cluster=~\"$cluster\",command=\"ADD\"}[10m]))) > 0",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Latency on Pod Deletion, P99",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(cluster, le) (rate(ovnkube_node_cni_request_duration_seconds_bucket{cluster=~\"$cluster\",command=\"DEL\"}[10m]))) > 0",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Changes Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(ovnkube_node_cni_request_duration_seconds_count{cluster=~\"$cluster\"}[10m])) by (cluster, err, command)",
     "legendFormat": "{{cluster}} {{command}} err={{err}}"
    }
   ]
  },
  {
   "title": "Latency on Pod Creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(ovnkube_node_cni_request_duration_seconds_bucket{cluster=~\"$cluster\",command=\"ADD\"}[10m])) by (cluster, le)) > 0",
     "legendFormat": "{{cluster}} p50 ADD"
    }
   ]
  },
  {
   "title": "Latency on Pod Deletion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(ovnkube_node_cni_request_duration_seconds_bucket{cluster=~\"$cluster\",command=\"DEL\"}[10m])) by (cluster, le)) > 0",
     "legendFormat": "{{cluster}} p50 DEL"
    }
   ]
  },
  { "title": "TCP Latency Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Average Connection Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000000)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Maximum Connection Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000000)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Minimum Connection Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000000)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "TCP Connection Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000)",
     "legendFormat": "{{cluster}} min"
    },
    {
     "expr": "max by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000)",
     "legendFormat": "{{cluster}} max"
    },
    {
     "expr": "avg by (cluster) (pod_network_connectivity_check_tcp_connect_latency_gauge{cluster=~\"$cluster\"} / 1000000)",
     "legendFormat": "{{cluster}} avg"
    }
   ]
  },
  { "title": "Control Plane Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Control Plane CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"ovnkube-master.*|ovnkube-control-plane-.*\",namespace=\"openshift-ovn-kubernetes\",container!~\"POD|\"}[10m])) by (cluster, pod) * 100",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Control Plane RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",pod=~\"ovnkube-master-.*|ovnkube-control-plane-.*\",namespace=\"openshift-ovn-kubernetes\",container!~\"POD|\"}) by (cluster, pod)",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  { "title": "Worker Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Top 10 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"ovnkube-.*\",namespace=\"openshift-ovn-kubernetes\",container=\"ovn-controller\"}[10m]) * 100)",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_rss{cluster=~\"$cluster\",pod=~\"ovnkube-node-.*\",namespace=\"openshift-ovn-kubernetes\",container=\"ovn-controller\"}) by (cluster, pod))",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 ovs-vswitchd CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",id=\"/system.slice/ovs-vswitchd.service\"}[10m]) * 100)",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  },
  {
   "title": "Top 10 ovs-vswitchd RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_rss{cluster=~\"$cluster\",id=\"/system.slice/ovs-vswitchd.service\"}) by (cluster, node))",
     "legendFormat": "{{cluster}} {{node}}"
    }
   ]
  }
 ]
}